# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.13.1-14-gfbd67ae
_src_path: gh:tsvikas/python-template
format_tool: black
get_package_version_from_vcs: true
github_user: tsvikas
has_cli: true
jupyter_files: forbid
license: MIT
package_description: display jupyter notebooks in the terminal.
package_name: nbcat
project_name: nbcat
python_min: 9
user_email: tsvikas@gmail.com
user_name: Tsvika Shapira
year: 2025
