name: Lint and test

on: [push, pull_request]

jobs:
  black:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          jupyter: false
          version: "~=25.0"
  ruff-lint:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
  pre-commit:
    if: ${{ always() }}
    env:
      COLUMNS: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@v5
      - uses: pre-commit/action@v3.0.1
  test:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resolution:
          - "no-upgrade"
          - "highest"
          - "lowest"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        allow-failure: [false]
        include:
          # map resolution to resolution-args
          - resolution: "no-upgrade"
            resolution-args: "--no-upgrade"
          - resolution: "highest"
            resolution-args: "--upgrade --resolution highest"
          - resolution: "lowest"
            resolution-args: "--upgrade --resolution lowest-direct"
          # add prerelease versions
          - resolution: "prerelease"
            resolution-args: "--upgrade --resolution highest --prerelease allow"
            python-version: "3.13"
            allow-failure: true
          - resolution: "prerelease"
            resolution-args: "--upgrade --resolution highest --prerelease allow"
            python-version: "3.14"
            allow-failure: true
    continue-on-error: ${{ matrix.allow-failure }}
    name: test-py${{ matrix.python-version }}-${{ matrix.resolution }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --group test ${{ matrix.resolution-args }}
      - name: Run tests
        run: uv run pytest
